### ISSUE TITLE
[v1] Support single pass instancing for VR

### ISSUE THREAD

**Issue by mob-sakai** [mob-sakai/SoftMaskForUGUI#85] opened 2020-05-09 13:34 UTC
ref: #48 #79 

- Generate two soft mask buffers for both eyes
- Selecting one of the soft mask buffers using `unity_StereoEyeIndex` variable.
```
lerp(_leftEye, _rightEye, unity_StereoEyeIndex);
```

https://docs.unity3d.com/Manual/SinglePassInstancing.html

**Comment by maskedmouse** [comment] 2020-05-26 10:03
How's the progress of this issue?
If you want me to test the functionality, let me know. I've got an Oculus GO.

**Comment by mob-sakai** [comment] 2020-05-27 07:30
@maskedmouse 
Thanks!
So far no progress has been made...

**Comment by mob-sakai** [comment] 2020-06-09 05:31
[SoftMask_VRTest.zip](https://github.com/mob-sakai/SoftMaskForUGUI/files/4750139/SoftMask_VRTest.zip)

WIP: Experimental version with support for multi-pass, single-pass and single-pass instancing.
- Scene view is broken.
- 2 RenderTextures for soft mask buffer.
- The scripts are not optimized.
- single-pass instancing is not tested. (It doesn't support Mac)

Open `Assets/VRTest.unity` and build it.

![](https://user-images.githubusercontent.com/12690315/84107059-bb54e080-aa57-11ea-8a56-f69a79e7830d.png)

**Comment by maskedmouse** [comment] 2020-06-09 08:02
I've tested it with Unity 2019.3.15 without success.

Just a few remarks:
- In 2019.3 the `PlayerSettings.virtualRealitySupported` is marked as deprecated but still functional.
- upgrading to 2019.3 some API got replaced automatically. Usually VRSettings => XRSettings
- I had to replace the Mock HMD with Oculus SDK. Which is logical because the Oculus GO doesn't work with a Mock HMD sdk.

I've made a screen capture of the result:
![Oculus GO 2019 3 15](https://user-images.githubusercontent.com/3502325/84120442-22619d80-aa36-11ea-9825-90a3eef134a4.png)

I noticed the stereo rendering mode for Oculus is Single Pass Multiview.
In the future 2020.1+ the XR Management package must be used. Which also has 2 options, Multipass or Multiview. Which in our case would be Single Pass Multiview.
I have not tried the new XR Management package yet with this solution. But I'd expect it to be the same as it is Single Pass Multiview.

For PC Oculus I cannot test right now (which can be Single Pass Instanced). I could test this later if you want.

**Comment by mob-sakai** [comment] 2020-06-09 08:39
I don't know why Unity-chan are not displayed.
Instead, gray rectangles are displayed...
Are Unity-chans displayed in editor?

**Comment by mob-sakai** [comment] 2020-06-09 08:46
Yes, The XR Management package should be supported in the future.

XR configuration in my environment:
![](https://user-images.githubusercontent.com/12690315/84126098-72615400-aa78-11ea-8f1c-d408d3b67ba8.png)

BTW, does multi pass render mode work well?

**Comment by mob-sakai** [comment] 2020-06-09 09:25
It appears to be working fine on my Android device.
- Sony Xperia XZ
- Mock HMD
- Android 8.0
- Multi pass/Single pass with multi-view

![image](https://user-images.githubusercontent.com/12690315/84130647-7e501480-aa7e-11ea-8cbb-a72036b769f9.png)
![image](https://user-images.githubusercontent.com/12690315/84130620-75f7d980-aa7e-11ea-909d-1ab04208fca3.png)

**Comment by maskedmouse** [comment] 2020-06-09 10:02
> I don't know why Unity-chan are not displayed.
> Instead, gray rectangles are displayed...
> Are Unity-chans displayed in editor?
Yes they are displayed in the editor.

> BTW, does multi pass render mode work well?
I've used the new XR Management SDK with Multipass and that seems to work.

![Oculus GO 2019 3 15 XR Management](https://user-images.githubusercontent.com/3502325/84134530-01ef0e80-aa49-11ea-99d9-77dcbfbc02a7.png)

**Comment by mob-sakai** [comment] 2020-06-09 13:15
Please try this.
[SoftMaskUGUI-VR-2.zip](https://github.com/mob-sakai/SoftMaskForUGUI/files/4752337/SoftMaskUGUI-VR-2.zip)

Open `Assets/VRTest.unity` and build it.
The scene contains a non-soft-maskable image.

**Comment by maskedmouse** [comment] 2020-06-09 14:08
> 
> 
> Please try this.
> [SoftMaskUGUI-VR-2.zip](https://github.com/mob-sakai/SoftMaskForUGUI/files/4752337/SoftMaskUGUI-VR-2.zip)
> 
> Open `Assets/VRTest.unity` and build it.
> The scene contains a non-soft-maskable image.

The result is that the soft masked items are still gray squares. The regular non-soft-maskable image is displayed fine.

![Oculus GO 2019 3 15 (2)](https://user-images.githubusercontent.com/3502325/84157760-66bb6080-aa6b-11ea-9d1c-f9a1161477e5.png)

**Comment by mob-sakai** [comment] 2020-06-09 15:34
Please try this.
[SoftMaskUGUI-VR-3.zip](https://github.com/mob-sakai/SoftMaskForUGUI/files/4753141/SoftMaskUGUI-VR-3.zip)

**Comment by maskedmouse** [comment] 2020-06-10 08:30
I've updated to the LTS release 2019.4.0f1
The image is now totally gone.

![Oculus GO 2019 4 0f1](https://user-images.githubusercontent.com/3502325/84245105-dc273f80-ab04-11ea-881e-53b8e9b28ded.png)

I'm using the Android Logcat 1.2.0-preview package to read out the output logs.
I notice there is an OpenGL error. Not sure if it is related to this. But it is worth mentioning.
`2020/06/10 10:25:36.777 31818 31833 Error Unity OPENGL NATIVE PLUG-IN ERROR: GL_INVALID_OPERATION: Operation illegal in current state `
It might be a thing of 2019.4 though.

**Comment by mob-sakai** [comment] 2020-06-10 08:41
Wow!

**Comment by mob-sakai** [comment] 2020-06-10 08:44
OK, let's test another shader...

**Comment by mob-sakai** [comment] 2020-06-10 09:16
![](https://user-images.githubusercontent.com/12690315/84249673-077e4e80-ab46-11ea-8923-d2b319a23b15.png)

[SoftMaskUGUI-VR-4.zip](https://github.com/mob-sakai/SoftMaskForUGUI/files/4757392/SoftMaskUGUI-VR-4.zip)

- A shader that maps the soft mask buffer and image UVs as rgb.

**Comment by maskedmouse** [comment] 2020-06-10 09:29
I'm getting the exact same result as before.
Image is not showing.

**Comment by mob-sakai** [comment] 2020-06-10 09:35
Oh, I was making a mistake!
Please comment out line 101 of `UI-Default-SoftMaskable.shader`.

```
//UNITY_DECLARE_SCREENSPACE_TEXTURE(_MainTex);
```

If you comment out the same file in `SoftMaskUGUI-VR-3.zip`, it may work.

**Comment by mob-sakai** [comment] 2020-06-10 09:38
Oh, I was making a mistake!
Please fix `UI-Default-SoftMaskable.shader` as following:

```
// line 101
//UNITY_DECLARE_SCREENSPACE_TEXTURE(_MainTex); // Comment out
sampler2D _MainTex; // ADD
```

If you comment out the same file in `SoftMaskUGUI-VR-3.zip`, it may work.

**Comment by maskedmouse** [comment] 2020-06-10 09:40
That seems to do the trick!

![Oculus GO 2019 4 0f1 removed Screenspace Declaration](https://user-images.githubusercontent.com/3502325/84252617-1eee1500-ab0f-11ea-9519-dea0cf89dd51.png)

I'll change it to the third iteration and test that one as well.

**Comment by maskedmouse** [comment] 2020-06-10 09:52
Yeah awesome!

![Oculus GO 2019 4 0f1 Fixed](https://user-images.githubusercontent.com/3502325/84253915-cd468a00-ab10-11ea-87a3-22c9b64e76d1.png)

**Comment by mob-sakai** [comment] 2020-06-10 09:55
👏👏👏👏

**Comment by mob-sakai** [comment] 2020-06-10 10:00
OK, VR support is the next step:
- [ ] Fix scene view
- [ ] 1 soft mask buffer for both eyes
- [ ] Optimize the scripts

**Comment by maskedmouse** [comment] 2020-06-24 08:14
I've received news about the Oculus GO no longer being supported after 4 december 2020.
I've tested the Oculus Quest with the solution you've made and it works there as well.
All that remains is the actual implementation of the solution into the package.

**Comment by mob-sakai** [comment] 2020-06-24 08:44
:+1:

**Comment by maskedmouse** [comment] 2020-07-30 10:24
I'm trying to get an Oculus Quest build ready but I'm uncertain whether the package could be used in the last state you've posted. It think it could be used, because it works in a release build. It is just not in an optimal state yet right?
As you've listed you want to create a singular Buffer for both eyes (I guess to preserve memory as you require double the texture memory now) and optimizing the scripts.

The only bug that I can find is that the Game View without VR enabled the softmask is broken.
Not a big issue for me since I have VR enabled all the time but might be worth noting.
I'll be looking forward to the release of the feature. In the meanwhile, I guess I'll use the solution as is since it seems to work.

**Comment by mob-sakai** [comment] 2020-07-30 11:11
:+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Comment by mob-sakai** [comment] 2020-09-08 01:44
WIP

**Comment by ruben-ivre** [comment] 2020-11-25 15:01
I'm very interested on this too, any updates? I have access to plenty of VR devices, so let me know if you want to test anything.

**Comment by mob-sakai** [comment] 2020-11-26 16:00
@ruben-ivre :+1:

**Comment by maskedmouse** [comment] 2021-01-05 13:53
It seems like in Unity 2020.2.1 the SoftMask is broken again. Perhaps this is due to an Universal Render Pipeline update.
Reverting back to Unity 2020.1.x and it works again.

**Comment by mob-sakai** [comment] 2021-01-06 09:42
OMG😇

**Comment by maskedmouse** [comment] 2021-01-13 15:34
Update:
When creating a small reproduction project, it seems to work fine in the editor with the latest SoftMasking package.
But once it is built for the Oculus Quest (Android) it fails, same as before the fix.

**Comment by nagoya0** [comment] 2024-06-26 18:57
Do you have any updates on this?

**Closed** 2024-07-17 10:36 UTC
Labels: enhancement
