### ISSUE TITLE
Incorrect behavior when a world space canvas and an overlay canvas are enabled together

### ISSUE THREAD

**Issue by noam2000** [mob-sakai/SoftMaskForUGUI#107] opened 2020-10-08 02:06 UTC
When there are two canvases enabled at the same time, where one's render mode is set to "World Space" and the other to "Screen Space - Overlay", and both have graphics that use Soft Mask, they tend to conflict with each other and produce undesired results, such as the mask not working.

**To Reproduce**

1. Create two canvases, one set to World Space and the other to Screen Space - Overlay. Give each a Soft Mask and a graphic with Soft Maskable on. For reference:

![image](https://user-images.githubusercontent.com/72533507/95406038-1d4c2680-0922-11eb-93be-b1fe2c17b2cf.png)
![image](https://user-images.githubusercontent.com/72533507/95406747-db23e480-0923-11eb-8580-be2637f48331.png)
![image](https://user-images.githubusercontent.com/72533507/95406771-e9720080-0923-11eb-9782-d9d8a3850b49.png)

2. You should notice that one or the other breaks and doesn't produce the desired results. If you disable a canvas (or the Soft Mask on that canvas), then the other graphic will work properly.

![image](https://user-images.githubusercontent.com/72533507/95406183-7b790980-0922-11eb-901a-606d620103a7.png)
_The red graphic is the one in World Space, and the green one is in Overlay. They have the same mask, but only one of them works._

**Expected behavior**
Both masks should work together without conflict.

**Environment**
 - Version 1.0.0-preview.13
 - Platform: Windows [Editor & Standalone]
 - Unity version: 2019.3.0f6
 - Build options: Mono, Net 4.x, HDRP

**Additional context**
Ticking "Use Stencil" in the Soft Maskable kind of solves the issue, but produces some.. not very soft results as you'd expect from the component.

![image](https://user-images.githubusercontent.com/72533507/95406668-9bf59380-0923-11eb-8f47-ccd4c7d27897.png)

Hopefully it's something that can be fixed. Thank you for your time :)

**Comment by mob-sakai** [comment] 2020-10-08 05:45
@noam2000 
Thank you for reporting.
Could you please attach a minimal project (included `Assets`, `Packages` and `ProjectSettings` directories) that reproduces the issue?

**Comment by noam2000** [comment] 2020-10-08 13:26
Here you go:
[SoftMaskIssueRepro.zip](https://github.com/mob-sakai/SoftMaskForUGUI/files/5348098/SoftMaskIssueRepro.zip)

**Comment by mob-sakai** [comment] 2020-10-08 15:09
@noam2000 
Thanks.

I found a problem with the shader for the scene view.
I commented out [the part](https://github.com/mob-sakai/SoftMaskForUGUI/blob/upm/Shaders/SoftMask.cginc#L28-L37) and it works in the game view.
![](https://user-images.githubusercontent.com/12690315/95476837-a6b33580-09c2-11eb-8303-ad8e3986481c.png)

**Comment by noam2000** [comment] 2020-10-08 15:33
@mob-sakai 

I commented out the lines you highlighted, but I'm getting some slightly.. different results. This is from the game view, on the same repro project I've sent.

![image](https://user-images.githubusercontent.com/72533507/95480559-b156d600-0994-11eb-8e6c-7a6cfba35a36.png)

**Comment by mob-sakai** [comment] 2020-10-08 15:47
Sorry, I was a little wrong.

Comment out here:
https://github.com/mob-sakai/SoftMaskForUGUI/blob/upm/Shaders/SoftMask.cginc#L28-L34

And change here to `#if UNITY_UV_STARTS_AT_TOP`
https://github.com/mob-sakai/SoftMaskForUGUI/blob/upm/Shaders/SoftMask.cginc#L35

**Comment by mob-sakai** [comment] 2020-10-08 15:59
The issue seems to be fixed in `v1.0.0-preview.14`.
![](https://user-images.githubusercontent.com/12690315/95479330-994b7a80-09c5-11eb-8270-a37293526770.png)

Please try it!

**Closed** 2020-10-08 16:00 UTC
Labels: bug, released on @preview
